#!/bin/bash

rules=$1
sentences=$2
output=$3

# Fill in the blank line with the command that will run your parser using the
# binarized rules and their counts from '$rules', so that all lines in
# '$sentences' are parsed and the result is saved to '$output'.
#
##############################################################################

##############################################################################
#
# Make sure the script works by running
# ./parse data/wsj2-21.blt data/wsj24.txt output.txt
python -i main.py $rules $sentences temp.txt
cat temp.txt | ./eval/munge-trees -rw > $output
