#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "fractal.h"
#include "image.h"


/*
	generate and save the entire fractal
	returns:	0 if successful
				1 otherwise
*/
int generate_fractal(char *file, float width, float height, int workers) {
	/*	TODO: use fork(), mmap(), and munmap() to create a region of shared memory
			to store fractal data, as generated by several child processes	*/
	
	size_t size = sizeof(color_t)*width*height;

	color_t *fractal_data = mmap(NULL, size, 
		PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANONYMOUS, -1 , 0);

	float num_rows = height/workers;
	float y;

	pid_t work_pids[workers];
	pid_t curr_child;

	for(int i=0; i<workers; i++){
		y=i*num_rows;

		switch( (curr_child = fork())  ){
		    case -1:
			perror("fork");
			break;

		    case 0:
			generate_fractal_region( fractal_data, width, height, y, num_rows);
			munmap(fractal_data, size);
			exit(0);
			//child logic
			break;

		    default:
			work_pids[i] = curr_child;
			break;
		}

	
	}
	for(int i = 0; i<workers; i++){
		waitpid( work_pids[i], NULL, 0);
	}

	printf("%s\n", file);
	if( save_image_data( file, fractal_data, width, height) ){
		perror("stderr");
		free(fractal_data);
		return 1;
	}

	printf("Complete \n");
	return 0;
}
