#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$PROJ = "dataproj";
$SERVER_NAME = "cs33.cs.brown.edu";
$SERVER_PORT = 33003;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
